site_name: Trevor Wieland - The Docs
site_description: "Machine Learning, Data Science, Mathematics, and an unhealthy apetite for Red Bull."
repo_url: "https://github.com/trevorWieland/"
repo_name: "My GitHub"
copyright: Copyright &copy; 2023 Trevor Wieland

theme:
  name: "material"
  features:
  - announce.dismiss
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
    scheme: slate
    primary: deep purple
    accent: purple

plugins:
  - search

nav:
  - Home:
    - Home: index.md
  - Major Projects:
    - Pokemon-Playing AI: projects/pokemon-playing-ai.md
  - Worklife:
    - Virtusize: work/virtusize.md
    - Rakuten Mobile: work/rakuten-mobile.md
    - Goody Goody: work/goody-goody.md
  - Write-Ups:
    - AI in the Retail Space: gists/ai-retail-space.md
  - About:
    - About Me: about/the-author.md
    - Cat Photos: about/cat-photos.md